search_criteria:
  - q: "language:python stars:100000..500000"
    per_page: 100
    # Python репозитории с 100000 до 500000 звезд

  - q: "language:python stars:10001..99999"  
    per_page: 100
    # Python репозитории с 10000 до 100000 звезд

  - q: "language:python stars:1001..10000"
    per_page: 100 
    # Python репозитории с 1000 до 10000 звезд

  - q: "language:python stars:101..1000"
    per_page: 100
    # Python репозитории со 100 до 1000 звезд

  - q: "language:python stars:<100"
    per_page: 100
    # Python репозитории с < чем 100 звездами

  - q: "language:python stars:1000..10000 topic:security"
    per_page: 100
    # Python репозитории по теме "security" с 1000 до 10000 звезд

  - q: "language:python stars:1000..10000 topic:web topic:api"
    per_page: 100
    # Python репозитории по темам "web" и "api" с 1000 до 10000 звезд

  - q: "language:python stars:1000..10000 topic:machine-learning topic:data-science"
    per_page: 100
    # Python репозитории по темам "machine-learning" и "data-science" с 1000 до 10000 звезд

  - q: "language:python stars:1000..10000 topic:iot"
    per_page: 100
    # Python репозитории по теме "iot" с 1000 до 10000 звезд

  - q: "language:python stars:1000..10000 topic:blockchain"
    per_page: 100
    # Python репозитории по теме "blockchain" с 1000 до 10000 звезд

  - q: "stars:>5000 topic:security"
    per_page: 100
    # Репозитории по теме "security" с более чем 5000 звезд

  - q: "stars:>75000 topic:web topic:api"
    per_page: 100
    # Репозитории по темам "web" и "api" с более чем 75000 звезд

  - q: "stars:10000..75000 topic:machine-learning topic:data-science" 
    per_page: 100
    # Репозитории по темам "machine-learning" и "data-science" с 10000 до 75000 звезд

  - q: "stars:1000..10000 topic:iot"
    per_page: 100
    # Репозитории по теме "iot" с 1000 до 10000 звезд

  - q: "stars:1000..10000 topic:blockchain"
    per_page: 100
    # Репозитории по теме "blockchain" с 1000 до 10000 звезд